# Generated by Django 6.0 on 2026-03-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intend_id',
            new_name='stripe_payment_intent_id',
        ),
    ]
